version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    image: rs_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://appuser:apppass@db:5432/appdb
      INSTANCE_ID: ${INSTANCE_ID:-}
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  db-data:
